WITH CTE AS (
	INSERT INTO #TABLE_NAME
	(	
		#COLUMNS
	)
	VALUES
	(
		#PARAMETER_NAMES
	)
	ON CONFLICT DO NOTHING
	RETURNING #PRIMARY_KEY
)
SELECT #PRIMARY_KEY FROM CTE
 UNION ALL
SELECT #PRIMARY_KEY FROM #TABLE_NAME #TABLE_ALIAS WHERE #UNIQUE_KEY_FILTERS;