namespace MelloSilveiraTools.Core.Managers.File;

/// <summary>
/// Represents the location and naming details of a document or report generated by the application.
/// Facilitates file tracking, user exports, and auditable data persistence.
/// </summary>
/// <param name="Uri">Directory path where the file is stored.</param>
/// <param name="Name">Corresponding file name.</param>
public readonly record struct FileData(string Uri, string Name)
{
    /// <summary>
    /// Initializes file metadata from an existing file information handle.
    /// </summary>
    /// <param name="fileInfo">Reference to the physical file.</param>
    public FileData(FileInfo fileInfo) : this(fileInfo.DirectoryName!, fileInfo.Name) { }
}
