//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MelloSilveiraTools.Infrastructure.Database.Sql.Provider {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SqlResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SqlResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MelloSilveiraTools.Infrastructure.Database.Sql.Provider.SqlResource", typeof(SqlResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM #TABLE_NAME AS #TABLE_ALIAS
        ///#WHERE.
        /// </summary>
        internal static string DeleteTemplate {
            get {
                return ResourceManager.GetString("DeleteTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO #TABLE_NAME
        ///(	
        ///	#COLUMNS
        ///)
        ///VALUES
        ///	#VALUES
        ///RETURNING #PRIMARY_KEY;.
        /// </summary>
        internal static string InsertInBatchTemplate {
            get {
                return ResourceManager.GetString("InsertInBatchTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO #TABLE_NAME
        ///(	
        ///	#COLUMNS
        ///)
        ///VALUES
        ///(
        ///	#PARAMETER_NAMES
        ///)
        ///RETURNING #PRIMARY_KEY;.
        /// </summary>
        internal static string InsertTemplate {
            get {
                return ResourceManager.GetString("InsertTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WITH CTE AS (
        ///	INSERT INTO #TABLE_NAME
        ///	(	
        ///		#COLUMNS
        ///	)
        ///	VALUES
        ///	(
        ///		#PARAMETER_NAMES
        ///	)
        ///	RETURNING #PRIMARY_KEY
        ///)
        ///SELECT #PRIMARY_KEY FROM CTE
        /// UNION ALL
        ///SELECT #PRIMARY_KEY FROM #TABLE_NAME #TABLE_ALIAS WHERE #UNIQUE_KEY_FILTERS;.
        /// </summary>
        internal static string InsertWithUniqueKeyTemplate {
            get {
                return ResourceManager.GetString("InsertWithUniqueKeyTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///	#COLUMNS
        ///FROM #TABLE_NAME AS #TABLE_ALIAS
        ///#JOIN
        ///#WHERE
        ///#ORDERBY
        ///#OFFSET
        ///#LIMIT.
        /// </summary>
        internal static string SelectTemplate {
            get {
                return ResourceManager.GetString("SelectTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE #TABLE_NAME
        ///SET
        ///	#VALUES_TO_UPDATE
        ///#WHERE.
        /// </summary>
        internal static string UpdateTemplate {
            get {
                return ResourceManager.GetString("UpdateTemplate", resourceCulture);
            }
        }
    }
}
